### ISSUE TITLE
Option for exporting non-user-created data does not work

### ISSUE THREAD

**Issue by Rel1ct0** [CheckPointSW/ExportImportPolicyPackage#101]
It is not implemented in code, basically.

If I try to export policy with system-created services (like ssh, ldap etc.), they will not be added to the resulting tar.gz, which contradicts the description of default system behavior.

The problem is in "should_export" function in export_objects.py
    return "domain" in obj and obj["domain"]["domain-type"] in ["domain", "global domain"]
should be changed to
    return "domain" in obj and obj["domain"]["domain-type"] in ["domain", "global domain", "data domain"]

Also, this:
    parser.add_argument("--non-user-created", required=False, default="**false**", choices=["true", "false"],
                        help="Indicates whether to show only user created data.\nDefault: **true**")

**Comment by chkp-edenbr** [comment]
Hi @Rel1ct0 
The tool is purposefully implemented this way, there is no need to export-import system objects since they already exist on the machine.
