### ISSUE TITLE
NAT rulebase export issue

### ISSUE THREAD

**Issue by Manchuker1120** [CheckPointSW/ExportImportPolicyPackage#104]
Exporting NAT policy

Getting information from show-nat-rulebase

Retrieved 50 out of 4341 rules (1%)

Retrieved 100 out of 4341 rules (2%)

Retrieved 150 out of 4341 rules (3%)

Retrieved 200 out of 4341 rules (4%)

Retrieved 250 out of 4341 rules (5%)

Retrieved 300 out of 4341 rules (6%)

Retrieved 350 out of 4341 rules (8%)

Retrieved 400 out of 4341 rules (9%)

Retrieved 450 out of 4341 rules (10%)

Retrieved 500 out of 4341 rules (11%)

Retrieved 550 out of 4341 rules (12%)

Retrieved 600 out of 4341 rules (13%)

Retrieved 650 out of 4341 rules (14%)

Retrieved 700 out of 4341 rules (16%)

Retrieved 750 out of 4341 rules (17%)

Retrieved 800 out of 4341 rules (18%)

Retrieved 850 out of 4341 rules (19%)

Retrieved 900 out of 4341 rules (20%)

Retrieved 950 out of 4341 rules (21%)

Retrieved 1000 out of 4341 rules (23%)

Retrieved 1050 out of 4341 rules (24%)

Retrieved 1100 out of 4341 rules (25%)

Retrieved 1150 out of 4341 rules (26%)

Retrieved 1200 out of 4341 rules (27%)

Retrieved 1250 out of 4341 rules (28%)

Traceback (most recent call last):
  File "/app/tools/ExportImportPolicyPackage/import_export_package.py", line 73, in <module>
    export_package(client, args)
  File "/app/tools/ExportImportPolicyPackage/exporting/export_package.py", line 65, in export_package
    nat_data_dict, nat_unexportable_objects = export_nat_rulebase(show_package.data["name"], client)
  File "/app/tools/ExportImportPolicyPackage/exporting/export_nat_rulebase.py", line 13, in export_nat_rulebase
    rulebase_rules, general_objects = get_query_nat_rulebase_data(client, {"package": package})
  File "/app/tools/ExportImportPolicyPackage/exporting/export_objects.py", line 184, in get_query_nat_rulebase_data
    if "Automatic Generated Rules : " in rulebase_item["name"]:
KeyError: 'name'

**Comment by chkp-edenbr** [comment]
Is it possible you have nat sections in the exported rulebase that don't have a name?

**Comment by Manchuker1120** [comment]
![image](https://github.com/user-attachments/assets/afed064a-416a-4b8f-9865-07773fe8a43d)
Is it not allowed to use this name?

**Comment by chkp-edenbr** [comment]
It's a feature in the Smart Console that shows the user that text instead of leaving it empty if a name wasn't set, the section object itself doesn't have a name. I recommend adding names to such objects and then running the tool again.

**Comment by Manchuker1120** [comment]
ty    
i will add name to such objects
