### ISSUE TITLE
How to increase session timeout for API?

### ISSUE THREAD

**Issue by incubenet** [CheckPointSW/ExportImportPolicyPackage#15]
Hi,
We're using this tool.
There are so many objects in a group object in a rule.
So, it stops on the way to loading due to expired session timeout.
How to increase session timeout? As far as I know it is default 600.
Please refer the following screenshot.
![screenshot](https://user-images.githubusercontent.com/35084285/58788255-774e2500-8626-11e9-8674-d8f51b315f06.png)

Regards,

**Comment by incubenet** [comment]
Is there any update?

**Comment by chkp-yaelg** [comment]
Hi @incubenet thanks for your comment,
Currently we don't support increasing the session timeout. 
We will check this issue and update you with a fix next week.

**Comment by chkp-yaelg** [comment]
Hi @incubenet ,

We updated the tool with new option to change the session timeout with the flag "--session-timeout".
If you interested to learn how to change the code by yourself, you can see the relevant changes in the last pull request #16 .

Thank you for using our open source and we encourage you to share your suggestions in the future.

Regards,
Management API team.
