### ISSUE TITLE
Threat Prevention import fails - First Threat Prevention Layer cannot be moved from the policy

### ISSUE THREAD

**Issue by KrisBogaerts** [CheckPointSW/ExportImportPolicyPackage#17]
Failed to attach layers to package! Error: message: Validation failed with 1 blocking-error
code: err_validation_failed
blocking-errors:
- message: First Threat Prevention Layer cannot be moved from the policy.
. Import operation aborted.

It fails on on the Shared IPS layers but it is not used in the exported  policy.

[import_export.log](https://github.com/CheckPointSW/ExportImportPolicyPackage/files/3277093/import_export.log)

[api.log](https://github.com/CheckPointSW/ExportImportPolicyPackage/files/3277119/api.log)

**Comment by chkp-amiads** [comment]
Hi @KrisBogaerts , thanks for reporting on that issue. A Jira issue was opened and will be addressed in the next 2-3 days. We will update on that thread when after we will deliver a fix.

Please keep sharing your feedback with us while using our repositories. In addition, as it is an open source, we encourage you to contribute and suggest code fixes/improvements in the future.

Regards,
Amiad Stern (Management API Team Leader)

**Comment by chkp-shirango** [comment]
Hi @KrisBogaerts,
The bug was fixed. 
You are welcome to use tool version 4.2 and see if it works well for you.

Thanks
Shiran
