### ISSUE TITLE
Problem for the groups with same name

### ISSUE THREAD

**Issue by jongsooda** [CheckPointSW/ExportImportPolicyPackage#21]
Hello,

There is a problem.

If the group to be imported and the group that exists have the same name, The rule adds the existing group, not the renamed group when importing access-rule.

The groups have different members each other.

Please fix this.

**Comment by jongsooda** [comment]
also it 's same for Host and Network.

We think renamed objects have to be included in policy When importing such as "NAME_COLLISION_RESOLVED_group".

Please Check this.

Thank you

**Comment by incubenet** [comment]
I add above explanation.

Target Management Server already has database (object, policy).
We exported from source Management Server and imported to target Management Server.
When imported the package, duplicated objects were renamed with + NAME_COLLISION_RESOLVED.
However, imported rules use original objects instead of renamed objects.

It's so many objects to replace them.

**Comment by chkp-amiads** [comment]
@jongsooda , @incubenet , thanks for your valuable feedback, we will open CR on that issue.
Meanwhile i can offer a WA but first i would like to understand what do you mean "It's so many objects to replace them manually". Do you mean you have many objects that were collide or 1-2 collisions which appear a lot of times in policy?

**Comment by incubenet** [comment]
Because there are collision objects, we're not able to replace original object to newly objects manually in policy.

**Comment by chkp-amiads** [comment]
As a WA, are you familiar with the "replace" feature in the GUI? 

Will the following work for you?
1. Navigate to the relevant policy
2. find original object
3. right click on it and choose where used
4. at the upper right side of 'where used?' dialog, click replace
5. choose the newly-created object and mark the relevant places you would like it to be replaced

As i said, i understand the issue and we will work on finding solution to it, it might take us 1-2 weeks as we are on top of other urgent issues.

**Comment by incubenet** [comment]
Yes, It is.

**Comment by chkp-amiads** [comment]
Good. On any case @chkp-maxcalderon  is working on a fix and we will update here when delivered.

**Comment by chkp-amiads** [comment]
@jongsooda , @incubenet , issue was fixed (see https://github.com/CheckPointSW/ExportImportPolicyPackage/commit/b41caa73fe3386916b7cca7242c2a05a086030a0). 

Thanks for you feedback. I encourage you to keep helping us improve our products and offer fixes of your own.

Regards,
Amiad.
