### ISSUE TITLE
Question about -h option.

### ISSUE THREAD

**Issue by incubenet** [CheckPointSW/ExportImportPolicyPackage#24]
Hi,

Our specific desktop is not applied option feature even though I add the -h option or others.
I attach screenshot.
What should I check on it?

![screenshot](https://user-images.githubusercontent.com/35084285/63674769-3aa75980-c822-11e9-82c1-36071a4ae48c.png)

**Comment by chkp-maxcalderon** [comment]
@incubenet what machine do you use? The -h flag works fine on my machine

**Comment by incubenet** [comment]
On laptop, this occurs on the this laptop.
Others works well.
As I tried running same tool on another laptop, it worked well.
So, I'm not sure what I check.

**Comment by chkp-amiads** [comment]
Hi @incubenet , have you tried --help?

**Comment by incubenet** [comment]
Yes, but it is still issue.
I copied the tool which works well on other laptops and desktops.
But, this issue appears on this laptop only.
I tried re-installing python and SDK, but it was not resolved.
So, I'm not sure what I should check.

**Comment by chkp-amiads** [comment]
Since you say it is only for specific laptop, it seems like it is not related to code but to laptop. i don't have an idea what should be checked. I'm closing this issue.
