### ISSUE TITLE
can't import rule with a group in Install-On

### ISSUE THREAD

**Issue by verduynb** [CheckPointSW/ExportImportPolicyPackage#25]
We have many rules with groups in the install on.
The script has properly imported the group with dummy objects in it.
However it fails to import rules that uses this group in "Install On"

**Comment by chkp-niram** [comment]
Hey @verduynb, 
Does the import operation fails completely or does it finish and the rules are not imported properly?
If it fails, could you please attach the logs from the failure?

**Comment by verduynb** [comment]
I was able to import the ruleset. However the rules with groups of GW in "Install On" were missing.Regards

    Le mercredi 23 octobre 2019 03 h 49 min 28 s UTC−4, chkp-niram <notifications@github.com> a écrit :  
 
 
Hey @verduynb,
Does the import operation fails completely or does it finish and the rules are not imported properly?
If it fails, could you please attach the logs from the failure?

**Comment by tschuchort** [comment]
Hi, is this solved in the actual version?

**Comment by chkp-edenbr** [comment]
Hi,

Issues concerning importing-exporting simple-gateways and groups containing them have been fixed in the new release v5.8

Regards,
Eden
