### ISSUE TITLE
KeyError in "lists_and_dictionaries.py" on R80.30 take 111

### ISSUE THREAD

**Issue by raphael-precigout** [CheckPointSW/ExportImportPolicyPackage#26]
API version changed to 1.6 since R80.30 take 111 which leads to a keyerror when parsing singular_to_plural_dictionary from lists_and_dictionaries.py

**Comment by chkp-yaelg** [comment]
Thank you @raphael-precigout ,

We are aware to this issue and we will publish a fix in next release of jumbo. When the fix will be released it will be updated in [sk163942](https://supportcenter.checkpoint.com/supportcenter/portal?eventSubmit_doGoviewsolutiondetails=&solutionid=sk163942).
If you would like to get private HF, please contact support.
