### ISSUE TITLE
Support for Smart1-cloud

### ISSUE THREAD

**Issue by RN42-4u** [CheckPointSW/ExportImportPolicyPackage#31]
Can not log into Smart1 Cloud for pushing policy / items to Smart1-Cloud.  Suspect it's associated with different requirement to specify DNS name for management endpoint location and context id that is not captured / passed for login.

**Comment by RN42-4u** [comment]
The script will run with the following parameters:
Custom name for imported package (optional) = TestPkg
Management Server IP = <myurltomaasinstance>.maas.checkpoint.com
Management Server Port = 443
Management Server Domain = None
1. Change Settings
2. Run
99. Back
2
Please enter your username:
admin

Please enter your password:


You currently do not have a record of this server's fingerprint.
Server's fingerprint: <FINGERPRINT RECEIVED CORRECTLY>
Do you accept this fingerprint? [y/n] y
Fingerprint saved.
Login to management server failed. instance({
    "data": null,
    "error_message": "APIResponse received a response which is not a valid JSON.",
    "res_obj": {},
    "status_code": 506,
    "success": false
})

**Comment by chkp-royl** [comment]
Hi @RN42-4u, 
Thanks for reporting this issue. please do the following:
1. Reproduce the issue
2. Connect to Mgmt via SSH and execute api status -s
3. Send the output (.tgz file) + tool logs to royl@checkpoint.com

Thanks,
Roy

**Comment by chkp-royl** [comment]
Support will be added in Q3, 2022.

**Comment by chkp-royl** [comment]
Hi All,
We added support for Smart-1 Cloud to Export&Import tool and also to our python SDK.
Use argument '--cloud-mgmt-id' to pass Smart-1 Cloud management identifier.

Regards,
Roy

**Comment by watermelon-bru** [comment]
Hi All, 

I am trying to use the script to import with the parameters below and I am getting an error:

python3 import_export_package.py --skip-duplicate-objects true --cloud-mgmt-id xxxxxxxx

is the service identifier = --cloud-mgmt-id ?

<img width="1871" height="537" alt="Image" src="https://github.com/user-attachments/assets/158f5a24-5fb8-4f9f-aae9-f791481b7321" />


Custom name for imported package (optional) = xxxx-policy
Management Server IP = .maas.checkpoint.com
Management Server Port = 443
Management Server Domain = None


Please select authentication method:
1. Username & Password
2. API Key
99. Back
2
Please enter your API key:



Login to management server failed. APIResponse({
    "data": {
        "errors": [
            {
                "message": "b'error: 400\\n'"
            }
        ]
    },
    "error_message": "APIResponse received a response which is not a valid JSON.",
    "res_obj": {
        "data": {
            "errors": [
                {
                    "message": "b'error: 400\\n'"
                }
            ]
        },
        "status_code": 400
    },
    "status_code": 400,
    "success": false
})


Regards,
Thiago

**Comment by chkp-royl** [comment]
Hi @watermelon-bru ,

No. If you will go to 'API & SmartConsole' tab you can read the instructions and it should be the same.
Service identifier is part of the Management Server IP. For example, **royl-12345678.maas.checkpoint.com**
cloud-mgmt-id is the UID in the URL right after the service identifier, for example **da2e15f6-48f1-4f7a-a3e9-5da09a2c56b5**

`royl-12345678.maas.checkpoint.com/da2e15f6-48f1-4f7a-a3e9-5da09a2c56b5`

**Comment by watermelon-bru** [comment]
Hi @chkp-royl,

Thanks for the explanations, the import is now working!

Best Regards,
Thiago

**Comment by carlosrodelo-arch** [comment]
hi, excuse me when it ask about the credentials you use username and passowrd? or api key? i tried with the api but show me some errors, and i don´t know if i i´m doing it right
