### ISSUE TITLE
If changing import package name by '-n' option, Manual NAT is not imported.

### ISSUE THREAD

**Issue by jongsooda** [CheckPointSW/ExportImportPolicyPackage#32]
Hello,

If i do not use origin package name,  Manual NAT is not imported.

For example,
I exported package named "Standard".
and I want to import the package named "Standard-new"
The Security rule is imported but Manual NAT is not imported.

Manual NAT import in the package named "Standard" not "Standard-new".

Please, fix this.

Thank you.

**Comment by chkp-royl** [comment]
Hi @jongsooda ,
Thank you for pointing out this issue. In order to investigate it, please do the following:

1. Reproduce the issue
2. Connect to MGMT via SSH and execute 'api status -s'
3. Send the output (.tgz file) + tool logs to royl@checkpoint.com

Thanks,
Roy

**Comment by chkp-royl** [comment]
Hi @jongsooda ,
We fixed this issue in the new version of tool v1.1.
Please run again using latest version and let me know if you encounter any issue.

Thanks,
Roy
