### ISSUE TITLE
bulk import of new objects

### ISSUE THREAD

**Issue by adi0s** [CheckPointSW/ExportImportPolicyPackage#33]
hello it seems that it doesn't leverage bulk add-host, etc feature on higher version of API, it would improve overall speed of import process.

**Comment by chkp-royl** [comment]
Hi @adi0s ,
Thank you for posting this issue.
We will support that in the next versions of the tool.

Thanks,
Roy

**Comment by chkp-royl** [comment]
Hi @adi0s ,

We released new version of the tool that support add batch objects.
Please use latest version to enjoy the new feature.

Regards,
Roy
