### ISSUE TITLE
Migrate to Python3

### ISSUE THREAD

**Issue by goopilot** [CheckPointSW/ExportImportPolicyPackage#50]
Is there any plans to migrate this tool to support Python 3?

**Comment by chkp-royl** [comment]
Hi @goopilot ,
We are working to migrate tool to python 3 and it will be available in the next version of the tool.

Regards,
Roy

**Comment by chkp-shirango** [comment]
Hi @goopilot,
We released a new version 5.0 that supports Python 3.7. 
You are welcome to use tool version 5.0.

Regards,
Shiran
