### ISSUE TITLE
executing the script stops at line 106 from util.py

### ISSUE THREAD

**Issue by cybercheat** [CheckPointSW/ExportImportPolicyPackage#54]
I have tried to use this script and when it is running it stopped at line 106 from utils.py.
![code error](https://user-images.githubusercontent.com/49393592/131145090-f178b2bd-f55d-4a9e-85da-83dba96012e5.JPG)

**Comment by chkp-shirango** [comment]
Hi @cybercheat,
What version of Python did you use?

**Comment by cybercheat** [comment]
Hi it is python2 the command I'm running is python impot_export_package.py

I'm not sure if the checkpoint appliance has installed pyhton3 .

thanks

**Comment by chkp-shirango** [comment]
Hi,

Since version 5.0 of the tool, the tool supports Python 3.7.
Please use Python 3.7.


Thanks,
Shiran
