### ISSUE TITLE
error on export

### ISSUE THREAD

**Issue by WadesWeaponShed** [CheckPointSW/ExportImportPolicyPackage#61]
Exporting Access Control layers

Exporting Access Layer [P-memcf-asg-cl1 Security]

Retrieved 50 out of 993 rules (5%)

Retrieved 100 out of 993 rules (10%)

Retrieved 150 out of 993 rules (15%)

Retrieved 200 out of 993 rules (20%)

Retrieved 250 out of 993 rules (25%)

Retrieved 300 out of 993 rules (30%)

Retrieved 350 out of 993 rules (35%)

Retrieved 400 out of 993 rules (40%)

Retrieved 450 out of 993 rules (45%)

Retrieved 500 out of 993 rules (50%)

Retrieved 550 out of 993 rules (55%)

Retrieved 600 out of 993 rules (60%)

Retrieved 650 out of 993 rules (65%)

Retrieved 700 out of 993 rules (70%)

Retrieved 750 out of 993 rules (75%)

Retrieved 800 out of 993 rules (80%)

Retrieved 850 out of 993 rules (85%)

Retrieved 900 out of 993 rules (90%)

Retrieved 950 out of 993 rules (95%)

Retrieved 993 out of 993 rules (100%)

Traceback (most recent call last):

File "import_export_package.py", line 61, in <module>

export_package(client, args)

File "/var/ExportImportPolicy/exporting/export_package.py", line 44, in export_package

= export_access_rulebase(show_package.data["name"], access_layer["name"], access_layer["uid"], client, timestamp, tar_file)

File "/var/ExportImportPolicy/exporting/export_access_rulebase.py", line 16, in export_access_rulebase

get_query_rulebase_data(client, "access-rulebase", {"name": layer, "uid": layer_uid, "package": package})

File "/var/ExportImportPolicy/exporting/export_objects.py", line 115, in get_query_rulebase_data

check_for_export_error(general_object, client)

File "/var/ExportImportPolicy/utils.py", line 462, in check_for_export_error

general_object["type"] not in singular_to_plural_dictionary[client.api_version]):

KeyError: u'1.7.1'

**Comment by chkp-royl** [comment]
You are using old version of the tool which doesn't support the API version on the export machine.
Try use tool latest version and let me know if it's still happen.

Roy
