### ISSUE TITLE
Can't export log track

### ISSUE THREAD

**Issue by quabank** [CheckPointSW/ExportImportPolicyPackage#64]
does anyone can explain why this can't export these track log.

my policy before export
![2022-02-23_11-17-36](https://user-images.githubusercontent.com/89638667/155264246-432fff3e-7c71-4404-982a-1ba34c545aff.png)

my policy after import
![2222](https://user-images.githubusercontent.com/89638667/155264523-ea7d397a-6983-4d5c-aa93-b0fe77e1842f.png)

many thanks!

**Comment by chkp-edenbr** [comment]
Thanks for notifying us.
I will investigate this.
Thanks,
Eden

**Comment by chkp-edenbr** [comment]
Hi @quabank,

The issue is fixed and is in the latest release.

Thanks,
Eden
