### ISSUE TITLE
Error with importing policies

### ISSUE THREAD

**Issue by SemmieD** [CheckPointSW/ExportImportPolicyPackage#66]
Goodmorning,

on R81.10 with JHF45 is it no longer possible to import policies. I'll get the following error:

Failed to import service-tcp with name [tcp_2376]. Error: code: generic_err_invalid_parameter
message: This API request must contain only one of these - "use-default-timeout = true" or "timeout = <value>"

in Take 38 are the following release notes about the API:
PRJ-33865,PRHF-21129 | Security Management | When creating or updating a service object via Management API, it is not possible to specify a custom aggressive-aging timeout.

Is there somehow possible to put the session timeout via this tool?

**Comment by chkp-royl** [comment]
Hi @SemmieD,

Thank you for posting this issue.
We fixed that bug in the latest version of the tool v5.5.
Try to use latest version and let me know if you still get any error.

Regards,
Roy
