### ISSUE TITLE
Update minimum requirements for this script

### ISSUE THREAD

**Issue by chkp-phoneboy** [CheckPointSW/ExportImportPolicyPackage#79]
It's pretty clear that current versions of this tool (after 5.0) do not run on older systems.
Refer to the following thread: https://community.checkpoint.com/t5/Management/R81-10-Export-Import-policy-package/m-p/145368/highlight/true#M30311

I suggest the following (hopefully) small changes, mostly documentation related.

- First, current versions should check if Python3 is used and print a useful error message if the version isn't v3.7 (or whatever the required minimum version is).
- Instructions should be clear that Python3 is REQUIRED and how to obtain it for Check Point management (e.g. apply recent JHF on R80.40 and above)
- Provide a link to the last version that runs correctly on Python2 for older management versions.

**Comment by chkp-edenbr** [comment]
Hi @chkp-phoneboy,
Thanks for notifying us, necessary changes were added and available in new release v5.8.1.
Regards,
Eden
