### ISSUE TITLE
bad indent

### ISSUE THREAD

**Issue by adi0s** [CheckPointSW/ExportImportPolicyPackage#83]
python import_export_package.py -h
Traceback (most recent call last):
  File "import_export_package.py", line 9, in <module>
    from importing.import_package import import_package
  File "/home/admin/export_import/importing/import_package.py", line 6, in <module>
    from importing.import_objects import import_objects, add_tag_to_object_payload
  File "/home/admin/export_import/importing/import_objects.py", line 983
    elif field in ["inline-layer", "host", "exception-group-name", "rule-name", "action"]:
                                                                                         ^

**Comment by chkp-royl** [comment]
Hi @adi0s ,
This issue not reproduce in my environment.
Which python & tool version are you using?

**Comment by adi0s** [comment]
python3, just did fresh download from git to MDS server and it started to throw this

**Comment by chkp-royl** [comment]
We found the bad indent and fixed it.
Please use latest release v5.8.4: https://github.com/CheckPointSW/ExportImportPolicyPackage/releases/tag/v5.8.4

Thanks,
Roy
