### ISSUE TITLE
bug with option --force

### ISSUE THREAD

**Issue by pepjm** [CheckPointSW/ExportImportPolicyPackage#90]
Hi

bug with option --force crash
"len(self.options) no length for type None "

in:
    def display(self):
        Menu.menu_print(self.title, 1)
        for i in range(1, len(self.options)):

I solved adding 
    if self.options:

     def display(self):
        Menu.menu_print(self.title, 1)
        if self.options:
           for i in range(1, len(self.options)):

**Comment by chkp-edenbr** [comment]
Hi @pepjm ,
Thanks for notifying us, we will make sure it's fixed in the next released version.

**Comment by chkp-edenbr** [comment]
Fixed in new release v6.2.0
