### ISSUE TITLE
Script Does not support 1.9.1 Mgmt API

### ISSUE THREAD

**Issue by ruralsoonerboy** [CheckPointSW/ExportImportPolicyPackage#92]
I was testing the script on an SMS R81.20 JHF 53

I am getting an error as follows.
  File "import_export_package.py", line 73, in <module>
    export_package(client, args)
  File "/home/admin/ExportImportPolicyPackage-master/ExportImportPolicyPackage-master/exporting/export_package.py", line 44, in export_package
    = export_access_rulebase(show_package.data["name"], access_layer["name"], access_layer["uid"], client, timestamp, tar_file)
  File "/home/admin/ExportImportPolicyPackage-master/ExportImportPolicyPackage-master/exporting/export_access_rulebase.py", line 16, in export_access_rulebase
    get_query_rulebase_data(client, "access-rulebase", {"name": layer, "uid": layer_uid, "package": package})
  File "/home/admin/ExportImportPolicyPackage-master/ExportImportPolicyPackage-master/exporting/export_objects.py", line 116, in get_query_rulebase_data
    check_for_export_error(general_object, client)
  File "/home/admin/ExportImportPolicyPackage-master/ExportImportPolicyPackage-master/utils.py", line 480, in check_for_export_error
    general_object["type"] not in singular_to_plural_dictionary[client.api_version]):
KeyError: '1.9.1'

I was able to fix the error by adding a 1.9.1 section to the dictionary in lists_and_dictionaries.py
"1.9.1": {
        "access-role": "access-roles",
        "threat-profile": "threat-profiles",
        "host": "hosts",
        "network": "networks",
        "address-range": "address_ranges",
        "multicast-address-range": "multicast-address-ranges",
        "security-zone": "security-zones",
        "time": "times",
        "simple-gateway": "simple-gateways",
        "simple-cluster": "simple-clusters",
        "dynamic-object": "dynamic-objects",
        "trusted-client": "trusted-clients",
        "tags": "tags",
        "dns-domain": "dns-domains",
        "opsec-application": "opsec-applications",
        "data-center": "data-centers",
        "data-center-object": "data-center-objects",
        "service-tcp": "services-tcp",
        "service-udp": "services-udp",
        "service-icmp": "services-icmp",
        "service-icmp6": "services-icmp6",
        "service-sctp": "services-sctp",
        "service-rpc": "services-rpc",
        "service-other": "services-other",
        "service-dce-rpc": "services-dce-rpc",
        "application-site": "applications-sites",
        "application-site-category": "application-site-categories",
        "application-site-group": "application-site-groups",
        "vpn-community-meshed": "vpn-communities-meshed",
        "vpn-community-star": "vpn-communities-star",
        "placeholder": "placeholders",
        "administrator": "administrators",
        "group": "groups",
        "group-with-exclusion": "groups-with-exclusion",
        "service-group": "service-groups",
        "time-group": "time-groups",
        "application-group": "application-groups",
        "threat-protection": "threat-protections",
        "exception-group": "exception-groups",
        "generic-object": "",
        "access-layer": "access-layers",
        "access-section": "access-sections",
        "access-rule": "access-rules",
        "nat-layer": "nat-layers",
        "nat-section": "nat-sections",
        "nat-rule": "nat-rules",
        "threat-layer": "threat-layers",
        "threat-rule": "threat-rules",
        "threat-exception-section": "threat-exception-sections",
        "threat-exception": "threat-exceptions",
        "wildcard": "wildcards",
        "updatable-object": "updatable-objects",
        "https-layer": "https-layers",
        "https-section": "https-sections",
        "https-rule": "https-rules"
    },
    
I wanted to bring this to your attention, Thanks

**Comment by chkp-edenbr** [comment]
Hi @ruralsoonerboy ,
Thanks for notifying us!
issue fixed in new released version v6
Regards,
Eden
